# Generated by Django 3.2.2 on 2022-11-03 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivers',
            name='no_of_seats',
            field=models.IntegerField(),
        ),
    ]
