# Generated by Django 3.2.2 on 2022-11-03 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0002_alter_drivers_no_of_seats'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='drivers',
            new_name='Driver',
        ),
    ]
