# Generated by Django 3.2.2 on 2022-11-03 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0003_rename_drivers_driver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='st_destination',
            new_name='starting_destination',
        ),
    ]
