# Generated by Django 3.2.2 on 2022-11-03 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0004_rename_st_destination_driver_starting_destination'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Driver',
            new_name='Drivers',
        ),
    ]
