# Generated by Django 3.2.2 on 2022-11-03 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rider', '0002_rename_ride_rider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rider',
            old_name='u_destination',
            new_name='user_destination',
        ),
    ]
