# Generated by Django 3.2.2 on 2022-11-03 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rider', '0003_rename_u_destination_rider_user_destination'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rider',
            new_name='Riders',
        ),
    ]
